/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patni.com.view;

import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import patni.com.controller.ValidationUtil;
import patni.com.model.PartnerModel;


/**
 *
 * @author itiss
 */
public class Patni extends javax.swing.JFrame {
    private List<PartnerModel> availablePartners;
    private List<PartnerModel> marriedPartners;
    private java.awt.CardLayout cardLayout;
    /**
     * Creates new form Patni
     */
    public Patni() {
        initComponents();
        initializeLayout();
        startProgress();
        availablePartners = new LinkedList();
        marriedPartners = new LinkedList();
    }
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(LoadingPanel, "LoadingScreen");
        getContentPane().add(LoginPanel, "LoginScreen");
        getContentPane().add(HomePanel, "HomeScreen");
        getContentPane().add(AdminPanel, "AdminScreen");
        getContentPane().add(DatabasePanel, "DatabaseScreen");

        loadScreen("LoadingScreen");
    }
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i);
                }
                return null;
            }

            @Override
        protected void process(java.util.List<Integer> chunks) {
            int progress = chunks.get(chunks.size() - 1);
            ProgressBar.setValue(progress);

            // Update messages based on progress
            if (progress <= 30) {
                messageLabel.setText("Tying the knot...");
            } else if (progress <= 70) {
                messageLabel.setText("Setting the stage...");
            } else if (progress < 100) {
                messageLabel.setText("Dancing to the baraat...");
            } else {
                messageLabel.setText("Happily ever after!");
            }
        }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute();
    }
    
    
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    private void registertoAvailableTable(){
        DefaultTableModel model = (DefaultTableModel) AvailableTable.getModel();
        model.setRowCount(0);
        for(PartnerModel partner : availablePartners){
            model.addRow(new Object[]{partner.getId(), partner.getName(), partner.getReligion(), partner.getHeight(), partner.getAge(), partner.getJob(), partner.getSalary(), partner.getGender()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanel = new javax.swing.JPanel();
        AboutusButtonHome = new javax.swing.JButton();
        DatabaseButtonHome = new javax.swing.JButton();
        AdminButtonHome = new javax.swing.JButton();
        HomeButtonHome = new javax.swing.JButton();
        LogoMessageLabel3 = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        WelcomeMessagelabel = new javax.swing.JLabel();
        WelcomeMessagelabel1 = new javax.swing.JLabel();
        WelcomeMessagelabel2 = new javax.swing.JLabel();
        HomePageImage = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        GenderErrorLabel = new javax.swing.JLabel();
        AdminMessageLabel = new javax.swing.JLabel();
        AboutusButtonAdmin = new javax.swing.JButton();
        DatabaseButtonAdmin = new javax.swing.JButton();
        AdminButtonAdmin = new javax.swing.JButton();
        HomeButtonAdmin = new javax.swing.JButton();
        LogoMessageLabel = new javax.swing.JLabel();
        TfPartnerId = new javax.swing.JTextField();
        TfPartnerName = new javax.swing.JTextField();
        TfPartnerAge = new javax.swing.JTextField();
        TfPartnerJob = new javax.swing.JTextField();
        TfPartnerSalary = new javax.swing.JTextField();
        TfPartnerReligion = new javax.swing.JComboBox<>();
        TfPartnerGender = new javax.swing.JComboBox<>();
        TfPartnerHeight = new javax.swing.JComboBox<>();
        AddButtonAdmin = new javax.swing.JButton();
        UpdateButtonAdmin = new javax.swing.JButton();
        DeleteButtonAdmin = new javax.swing.JButton();
        MarriedButtonAdmin = new javax.swing.JButton();
        IdErrorLabel = new javax.swing.JLabel();
        NameErrorLabel = new javax.swing.JLabel();
        ReligionErrorLabel = new javax.swing.JLabel();
        AgeErrorLabel = new javax.swing.JLabel();
        HeightErrorLabel = new javax.swing.JLabel();
        JobErrorLabel = new javax.swing.JLabel();
        SalaryErrorLabel = new javax.swing.JLabel();
        AdminImage = new javax.swing.JLabel();
        DatabasePanel = new javax.swing.JPanel();
        AboutusButtonDatabase = new javax.swing.JButton();
        DatabaseButtonDatabase = new javax.swing.JButton();
        AdminButtonDatabase = new javax.swing.JButton();
        HomeButtonDatabase = new javax.swing.JButton();
        LogoMessageLabel1 = new javax.swing.JLabel();
        AvailableTablePanel = new javax.swing.JScrollPane();
        AvailableTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        DatabaseImage = new javax.swing.JLabel();
        AboutusPanel = new javax.swing.JPanel();
        AboutusButtonHome2 = new javax.swing.JButton();
        DatabaseButtonHome2 = new javax.swing.JButton();
        AdminButtonAdmin2 = new javax.swing.JButton();
        HomeButtonHome2 = new javax.swing.JButton();
        LogoMessageLabel2 = new javax.swing.JLabel();
        AdminImage2 = new javax.swing.JLabel();
        LoadingPanel = new javax.swing.JPanel();
        ProgressBar = new javax.swing.JProgressBar();
        messageLabel = new javax.swing.JLabel();
        LoadingScreenImage = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        TfLoginUsername = new javax.swing.JTextField();
        TfLoginPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        IncorrectLabelLogin = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        HomePanel.setMaximumSize(new java.awt.Dimension(1300, 1080));
        HomePanel.setMinimumSize(new java.awt.Dimension(1300, 1080));
        HomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AboutusButtonHome.setBackground(new java.awt.Color(255, 209, 102));
        AboutusButtonHome.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        AboutusButtonHome.setForeground(new java.awt.Color(50, 4, 10));
        AboutusButtonHome.setText("About us");
        AboutusButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutusButtonHomeActionPerformed(evt);
            }
        });
        HomePanel.add(AboutusButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 110, -1));

        DatabaseButtonHome.setBackground(new java.awt.Color(255, 209, 102));
        DatabaseButtonHome.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        DatabaseButtonHome.setForeground(new java.awt.Color(50, 4, 10));
        DatabaseButtonHome.setText("Database");
        DatabaseButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseButtonHomeActionPerformed(evt);
            }
        });
        HomePanel.add(DatabaseButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 110, -1));

        AdminButtonHome.setBackground(new java.awt.Color(255, 209, 102));
        AdminButtonHome.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        AdminButtonHome.setForeground(new java.awt.Color(50, 4, 10));
        AdminButtonHome.setText("Admin");
        AdminButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonHomeActionPerformed(evt);
            }
        });
        HomePanel.add(AdminButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 110, -1));

        HomeButtonHome.setBackground(new java.awt.Color(255, 209, 102));
        HomeButtonHome.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        HomeButtonHome.setForeground(new java.awt.Color(50, 4, 10));
        HomeButtonHome.setText("Home");
        HomeButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonHomeActionPerformed(evt);
            }
        });
        HomePanel.add(HomeButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 110, -1));

        LogoMessageLabel3.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 36)); // NOI18N
        LogoMessageLabel3.setForeground(new java.awt.Color(255, 255, 255));
        LogoMessageLabel3.setText("Shaadi Mitra");
        HomePanel.add(LogoMessageLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 60));

        WelcomeLabel.setFont(new java.awt.Font("Ananda Namaste", 1, 100)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 192, 97));
        WelcomeLabel.setText("Swagatam");
        HomePanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 470, 90));

        WelcomeMessagelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeMessagelabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeMessagelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeMessagelabel.setText("unique story. Begin your forever today!");
        WelcomeMessagelabel.setToolTipText("");
        HomePanel.add(WelcomeMessagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, 640, 40));

        WelcomeMessagelabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeMessagelabel1.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeMessagelabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeMessagelabel1.setText("At Shadi Mitra, we make finding your perfect life partner effortless and");
        HomePanel.add(WelcomeMessagelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 640, 40));

        WelcomeMessagelabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeMessagelabel2.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeMessagelabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeMessagelabel2.setText("meaningful. Discover connections that honor tradition and embrace your ");
        HomePanel.add(WelcomeMessagelabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 640, 40));

        HomePageImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Home Page.png"))); // NOI18N
        HomePanel.add(HomePageImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AdminPanel.setMaximumSize(new java.awt.Dimension(1300, 1080));
        AdminPanel.setMinimumSize(new java.awt.Dimension(1300, 1080));
        AdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GenderErrorLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.add(GenderErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 250, 20));

        AdminMessageLabel.setFont(new java.awt.Font("Ananda Namaste", 1, 50)); // NOI18N
        AdminMessageLabel.setForeground(new java.awt.Color(50, 4, 10));
        AdminMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminMessageLabel.setText("Admin Control");
        AdminPanel.add(AdminMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 330, 80));

        AboutusButtonAdmin.setBackground(new java.awt.Color(255, 209, 102));
        AboutusButtonAdmin.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        AboutusButtonAdmin.setForeground(new java.awt.Color(50, 4, 10));
        AboutusButtonAdmin.setText("About us");
        AboutusButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutusButtonAdminActionPerformed(evt);
            }
        });
        AdminPanel.add(AboutusButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 110, -1));

        DatabaseButtonAdmin.setBackground(new java.awt.Color(255, 209, 102));
        DatabaseButtonAdmin.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        DatabaseButtonAdmin.setForeground(new java.awt.Color(50, 4, 10));
        DatabaseButtonAdmin.setText("Database");
        DatabaseButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseButtonAdminActionPerformed(evt);
            }
        });
        AdminPanel.add(DatabaseButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 110, -1));

        AdminButtonAdmin.setBackground(new java.awt.Color(255, 209, 102));
        AdminButtonAdmin.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        AdminButtonAdmin.setForeground(new java.awt.Color(50, 4, 10));
        AdminButtonAdmin.setText("Admin");
        AdminButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonAdminActionPerformed(evt);
            }
        });
        AdminPanel.add(AdminButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 110, -1));

        HomeButtonAdmin.setBackground(new java.awt.Color(255, 209, 102));
        HomeButtonAdmin.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        HomeButtonAdmin.setForeground(new java.awt.Color(50, 4, 10));
        HomeButtonAdmin.setText("Home");
        HomeButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonAdminActionPerformed(evt);
            }
        });
        AdminPanel.add(HomeButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 110, -1));

        LogoMessageLabel.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 36)); // NOI18N
        LogoMessageLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoMessageLabel.setText("Shaadi Mitra");
        AdminPanel.add(LogoMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 60));

        TfPartnerId.setText("ID");
        TfPartnerId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerIdMouseClicked(evt);
            }
        });
        AdminPanel.add(TfPartnerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 250, -1));

        TfPartnerName.setText("Name");
        TfPartnerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerNameMouseClicked(evt);
            }
        });
        TfPartnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPartnerNameActionPerformed(evt);
            }
        });
        AdminPanel.add(TfPartnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 250, -1));

        TfPartnerAge.setText("Age");
        TfPartnerAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerAgeMouseClicked(evt);
            }
        });
        AdminPanel.add(TfPartnerAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 250, -1));

        TfPartnerJob.setText("Job");
        TfPartnerJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerJobMouseClicked(evt);
            }
        });
        AdminPanel.add(TfPartnerJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 250, -1));

        TfPartnerSalary.setText("Salary");
        TfPartnerSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerSalaryMouseClicked(evt);
            }
        });
        TfPartnerSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPartnerSalaryActionPerformed(evt);
            }
        });
        AdminPanel.add(TfPartnerSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 260, -1));

        TfPartnerReligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Religion", "Hinduism", "Buddhism", "Islam", "Kirant", "Christianity", "Bon", "Others" }));
        TfPartnerReligion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerReligionMouseClicked(evt);
            }
        });
        AdminPanel.add(TfPartnerReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 260, -1));

        TfPartnerGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Others" }));
        TfPartnerGender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerGenderMouseClicked(evt);
            }
        });
        TfPartnerGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPartnerGenderActionPerformed(evt);
            }
        });
        AdminPanel.add(TfPartnerGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 550, 250, -1));

        TfPartnerHeight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Height", "5'0", "5'1", "5'2", "5'3", "5'4", "5'5", "5'6", "5'7", "5'8", "5'9", "5'10", "5'11", "6'0", "6'1", "6'2", "6'3", "6'4", "6'5" }));
        TfPartnerHeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerHeightMouseClicked(evt);
            }
        });
        AdminPanel.add(TfPartnerHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 250, -1));

        AddButtonAdmin.setBackground(new java.awt.Color(0, 0, 0));
        AddButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        AddButtonAdmin.setForeground(new java.awt.Color(248, 250, 252));
        AddButtonAdmin.setText("Add");
        AddButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonAdminActionPerformed(evt);
            }
        });
        AdminPanel.add(AddButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, 90, 40));

        UpdateButtonAdmin.setBackground(new java.awt.Color(0, 0, 0));
        UpdateButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        UpdateButtonAdmin.setForeground(new java.awt.Color(248, 250, 252));
        UpdateButtonAdmin.setText("Update");
        UpdateButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonAdminActionPerformed(evt);
            }
        });
        AdminPanel.add(UpdateButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 100, 40));

        DeleteButtonAdmin.setBackground(new java.awt.Color(0, 0, 0));
        DeleteButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        DeleteButtonAdmin.setForeground(new java.awt.Color(248, 250, 252));
        DeleteButtonAdmin.setText("Delete");
        DeleteButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonAdminActionPerformed(evt);
            }
        });
        AdminPanel.add(DeleteButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 650, 90, 40));

        MarriedButtonAdmin.setBackground(new java.awt.Color(0, 0, 0));
        MarriedButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        MarriedButtonAdmin.setForeground(new java.awt.Color(248, 250, 252));
        MarriedButtonAdmin.setText("Married");
        MarriedButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarriedButtonAdminActionPerformed(evt);
            }
        });
        AdminPanel.add(MarriedButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 750, 90, 40));

        IdErrorLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.add(IdErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 250, 20));

        NameErrorLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.add(NameErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 250, 20));

        ReligionErrorLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.add(ReligionErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 250, 20));

        AgeErrorLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.add(AgeErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 250, 20));

        HeightErrorLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.add(HeightErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 250, 20));

        JobErrorLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.add(JobErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 250, 20));

        SalaryErrorLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.add(SalaryErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 250, 20));

        AdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Admin Page.png"))); // NOI18N
        AdminPanel.add(AdminImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1080));

        DatabasePanel.setMaximumSize(new java.awt.Dimension(1300, 1080));
        DatabasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AboutusButtonDatabase.setBackground(new java.awt.Color(255, 209, 102));
        AboutusButtonDatabase.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        AboutusButtonDatabase.setForeground(new java.awt.Color(50, 4, 10));
        AboutusButtonDatabase.setText("About us");
        AboutusButtonDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutusButtonDatabaseActionPerformed(evt);
            }
        });
        DatabasePanel.add(AboutusButtonDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 110, -1));

        DatabaseButtonDatabase.setBackground(new java.awt.Color(255, 209, 102));
        DatabaseButtonDatabase.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        DatabaseButtonDatabase.setForeground(new java.awt.Color(50, 4, 10));
        DatabaseButtonDatabase.setText("Database");
        DatabaseButtonDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseButtonDatabaseActionPerformed(evt);
            }
        });
        DatabasePanel.add(DatabaseButtonDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 110, -1));

        AdminButtonDatabase.setBackground(new java.awt.Color(255, 209, 102));
        AdminButtonDatabase.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        AdminButtonDatabase.setForeground(new java.awt.Color(50, 4, 10));
        AdminButtonDatabase.setText("Admin");
        AdminButtonDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonDatabaseActionPerformed(evt);
            }
        });
        DatabasePanel.add(AdminButtonDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 110, -1));

        HomeButtonDatabase.setBackground(new java.awt.Color(255, 209, 102));
        HomeButtonDatabase.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        HomeButtonDatabase.setForeground(new java.awt.Color(50, 4, 10));
        HomeButtonDatabase.setText("Home");
        HomeButtonDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonDatabaseActionPerformed(evt);
            }
        });
        DatabasePanel.add(HomeButtonDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 110, -1));

        LogoMessageLabel1.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 36)); // NOI18N
        LogoMessageLabel1.setForeground(new java.awt.Color(255, 255, 255));
        LogoMessageLabel1.setText("Shaadi Mitra");
        DatabasePanel.add(LogoMessageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 60));

        AvailableTablePanel.setBackground(new java.awt.Color(50, 4, 10));
        AvailableTablePanel.setBorder(null);
        AvailableTablePanel.setForeground(new java.awt.Color(50, 4, 10));
        AvailableTablePanel.setToolTipText("");
        AvailableTablePanel.setFocusable(false);

        AvailableTable.setBackground(new java.awt.Color(50, 4, 10));
        AvailableTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 176, 64)));
        AvailableTable.setForeground(new java.awt.Color(251, 176, 64));
        AvailableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Religion", "Age", "Height", "Job", "Salary", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AvailableTable.setOpaque(false);
        AvailableTable.setRowSelectionAllowed(false);
        AvailableTablePanel.setViewportView(AvailableTable);
        if (AvailableTable.getColumnModel().getColumnCount() > 0) {
            AvailableTable.getColumnModel().getColumn(0).setResizable(false);
            AvailableTable.getColumnModel().getColumn(1).setResizable(false);
            AvailableTable.getColumnModel().getColumn(2).setResizable(false);
            AvailableTable.getColumnModel().getColumn(3).setResizable(false);
            AvailableTable.getColumnModel().getColumn(4).setResizable(false);
            AvailableTable.getColumnModel().getColumn(5).setResizable(false);
            AvailableTable.getColumnModel().getColumn(7).setResizable(false);
        }

        DatabasePanel.add(AvailableTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 650, 350));

        jLabel2.setFont(new java.awt.Font("Ananda Namaste", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 176, 64));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome");
        DatabasePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 650, 90));

        DatabaseImage.setBackground(new java.awt.Color(50, 4, 10));
        DatabaseImage.setForeground(new java.awt.Color(251, 176, 64));
        DatabaseImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatabaseImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Database Page.png"))); // NOI18N
        DatabasePanel.add(DatabaseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1080));

        AboutusPanel.setMaximumSize(new java.awt.Dimension(1300, 1080));
        AboutusPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AboutusButtonHome2.setBackground(new java.awt.Color(255, 209, 102));
        AboutusButtonHome2.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        AboutusButtonHome2.setForeground(new java.awt.Color(50, 4, 10));
        AboutusButtonHome2.setText("About us");
        AboutusButtonHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutusButtonHome2ActionPerformed(evt);
            }
        });
        AboutusPanel.add(AboutusButtonHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 110, -1));

        DatabaseButtonHome2.setBackground(new java.awt.Color(255, 209, 102));
        DatabaseButtonHome2.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        DatabaseButtonHome2.setForeground(new java.awt.Color(50, 4, 10));
        DatabaseButtonHome2.setText("Database");
        DatabaseButtonHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseButtonHome2ActionPerformed(evt);
            }
        });
        AboutusPanel.add(DatabaseButtonHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 110, -1));

        AdminButtonAdmin2.setBackground(new java.awt.Color(255, 209, 102));
        AdminButtonAdmin2.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        AdminButtonAdmin2.setForeground(new java.awt.Color(50, 4, 10));
        AdminButtonAdmin2.setText("Admin");
        AdminButtonAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonAdmin2ActionPerformed(evt);
            }
        });
        AboutusPanel.add(AdminButtonAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 110, -1));

        HomeButtonHome2.setBackground(new java.awt.Color(255, 209, 102));
        HomeButtonHome2.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        HomeButtonHome2.setForeground(new java.awt.Color(50, 4, 10));
        HomeButtonHome2.setText("Home");
        HomeButtonHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonHome2ActionPerformed(evt);
            }
        });
        AboutusPanel.add(HomeButtonHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 110, -1));

        LogoMessageLabel2.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 36)); // NOI18N
        LogoMessageLabel2.setForeground(new java.awt.Color(255, 255, 255));
        LogoMessageLabel2.setText("Shaadi Mitra");
        AboutusPanel.add(LogoMessageLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 60));

        AdminImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Admin Page.png"))); // NOI18N
        AboutusPanel.add(AdminImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1080));

        LoadingPanel.setMaximumSize(new java.awt.Dimension(1300, 1080));
        LoadingPanel.setMinimumSize(new java.awt.Dimension(1300, 1080));
        LoadingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProgressBar.setBackground(new java.awt.Color(50, 4, 10));
        ProgressBar.setForeground(new java.awt.Color(207, 172, 108));
        ProgressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoadingPanel.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, 690, 30));

        messageLabel.setForeground(new java.awt.Color(251, 176, 64));
        LoadingPanel.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 650, 240, 20));

        LoadingScreenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Loading Page (Grid).png"))); // NOI18N
        LoadingPanel.add(LoadingScreenImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1080));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 1080));
        setMinimumSize(new java.awt.Dimension(1300, 1080));
        setSize(new java.awt.Dimension(1300, 1080));

        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfLoginUsername.setText("Username");
        LoginPanel.add(TfLoginUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 472, 300, 30));

        TfLoginPassword.setText("Password");
        LoginPanel.add(TfLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 542, 300, 30));

        jLabel1.setFont(new java.awt.Font("Ananda Namaste", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 209, 102));
        jLabel1.setText("Welcome");
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 390, 70));

        LoginButton.setBackground(new java.awt.Color(255, 209, 102));
        LoginButton.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(50, 4, 10));
        LoginButton.setText("Log in");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, -1, -1));

        IncorrectLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LoginPanel.add(IncorrectLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 300, 20));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LoginPageImage.png"))); // NOI18N
        LoginPanel.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String Username = TfLoginUsername.getText();
        String Password = new String(TfLoginPassword.getPassword());

        if ("Username".equals(Username) && "Password".equals(Password)){
            loadScreen("HomeScreen");
        }
        else{
            IncorrectLabelLogin.setText("Incorrect Username or Password");
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void HomeButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonAdminActionPerformed
        loadScreen("HomeScreen");
    }//GEN-LAST:event_HomeButtonAdminActionPerformed

    private void AdminButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminButtonAdminActionPerformed

    private void DatabaseButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseButtonAdminActionPerformed
        loadScreen("DatabaseScreen");
    }//GEN-LAST:event_DatabaseButtonAdminActionPerformed

    private void AboutusButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutusButtonAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutusButtonAdminActionPerformed

    private void AboutusButtonDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutusButtonDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutusButtonDatabaseActionPerformed

    private void DatabaseButtonDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseButtonDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatabaseButtonDatabaseActionPerformed

    private void AdminButtonDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonDatabaseActionPerformed
        loadScreen("AdminScreen");
    }//GEN-LAST:event_AdminButtonDatabaseActionPerformed

    private void HomeButtonDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonDatabaseActionPerformed
        loadScreen("HomeScreen");
    }//GEN-LAST:event_HomeButtonDatabaseActionPerformed

    private void AboutusButtonHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutusButtonHome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutusButtonHome2ActionPerformed

    private void DatabaseButtonHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseButtonHome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatabaseButtonHome2ActionPerformed

    private void AdminButtonAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminButtonAdmin2ActionPerformed

    private void HomeButtonHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonHome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonHome2ActionPerformed

    private void TfPartnerIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerIdMouseClicked
        IdErrorLabel.setText("");
        TfPartnerId.setText("");
    }//GEN-LAST:event_TfPartnerIdMouseClicked

    private void TfPartnerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerNameMouseClicked
        NameErrorLabel.setText("");
        TfPartnerName.setText("");
    }//GEN-LAST:event_TfPartnerNameMouseClicked

    private void TfPartnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPartnerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPartnerNameActionPerformed

    private void TfPartnerAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerAgeMouseClicked
        AgeErrorLabel.setText("");
        TfPartnerAge.setText("");
    }//GEN-LAST:event_TfPartnerAgeMouseClicked

    private void TfPartnerJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerJobMouseClicked
        TfPartnerJob.setText("");
        JobErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerJobMouseClicked

    private void TfPartnerSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerSalaryMouseClicked
        TfPartnerSalary.setText("");
        SalaryErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerSalaryMouseClicked

    private void TfPartnerSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPartnerSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPartnerSalaryActionPerformed

    private void TfPartnerReligionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerReligionMouseClicked
        ReligionErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerReligionMouseClicked

    private void TfPartnerGenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerGenderMouseClicked
        GenderErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerGenderMouseClicked

    private void TfPartnerGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPartnerGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPartnerGenderActionPerformed

    private void TfPartnerHeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerHeightMouseClicked
        HeightErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerHeightMouseClicked

    private void AddButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonAdminActionPerformed
        String id = TfPartnerId.getText();
        String name = TfPartnerName.getText();
        String religion = (String)TfPartnerReligion.getSelectedItem();
        String height = (String)TfPartnerHeight.getSelectedItem();
        String age = TfPartnerAge.getText();
        String job = TfPartnerJob.getText();
        String salary = TfPartnerSalary.getText();
        String gender = (String)TfPartnerGender.getSelectedItem();
        boolean isValid = ValidationUtil.isValidId(id, IdErrorLabel) &&
        ValidationUtil.isValidName(name, NameErrorLabel) &&
        ValidationUtil.isValidReligion(religion, ReligionErrorLabel) &&
        ValidationUtil.isValidAge(age, AgeErrorLabel)&&
        ValidationUtil.isValidHeight(height, HeightErrorLabel) &&
        ValidationUtil.isValidJob(job, JobErrorLabel) &&
        ValidationUtil.isValidSalary(salary, SalaryErrorLabel) &&
        ValidationUtil.isValidGender(gender, GenderErrorLabel);
        boolean matchfound = false;
        if (isValid){
            PartnerModel partner = new PartnerModel(id, name, religion, Short.parseShort(age),height, job, Integer.valueOf(salary), gender);
            for (PartnerModel part : availablePartners){
                if (part.getId().equals(partner.getId())){
                    matchfound = true;
                }
            }
            if (matchfound){
                IdErrorLabel.setText("Id already Exists");
            }
            else{
                availablePartners.add(partner);
                registertoAvailableTable();
            }
        }
    }//GEN-LAST:event_AddButtonAdminActionPerformed

    private void UpdateButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonAdminActionPerformed
        String id = TfPartnerId.getText();
        String name = TfPartnerName.getText();
        String religion = (String)TfPartnerReligion.getSelectedItem();
        String height = (String)TfPartnerHeight.getSelectedItem();
        String age = TfPartnerAge.getText();
        String job = TfPartnerJob.getText();
        String salary = TfPartnerSalary.getText();
        String gender = (String)TfPartnerGender.getSelectedItem();
        boolean isValid = ValidationUtil.isValidId(id, IdErrorLabel) &&
        ValidationUtil.isValidName(name, NameErrorLabel) &&
        ValidationUtil.isValidReligion(religion, ReligionErrorLabel) &&
        ValidationUtil.isValidAge(age, AgeErrorLabel)&&
        ValidationUtil.isValidHeight(height, HeightErrorLabel) &&
        ValidationUtil.isValidJob(job, JobErrorLabel) &&
        ValidationUtil.isValidSalary(salary, SalaryErrorLabel) &&
        ValidationUtil.isValidGender(gender, GenderErrorLabel);
        boolean matchfound = false;
        if(isValid){
            PartnerModel partner = new PartnerModel(id, name, religion, Short.parseShort(age),height, job, Integer.valueOf(salary), gender);
            for(PartnerModel part : availablePartners){
                if(part.getId().equals(partner.getId())){
                    availablePartners.remove(part);
                    availablePartners.add(partner);
                    registertoAvailableTable();
                    matchfound = true;
                }
            }
            if (!matchfound){
                IdErrorLabel.setText("Id doesnt exist");
            }

        }
    }//GEN-LAST:event_UpdateButtonAdminActionPerformed

    private void DeleteButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonAdminActionPerformed
        String id = TfPartnerId.getText();
        String name = TfPartnerName.getText();
        String religion = (String)TfPartnerReligion.getSelectedItem();
        String height = (String)TfPartnerHeight.getSelectedItem();
        String age = TfPartnerAge.getText();
        String job = TfPartnerJob.getText();
        String salary = TfPartnerSalary.getText();
        String gender = (String)TfPartnerGender.getSelectedItem();
        boolean isValid = ValidationUtil.isValidId(id, IdErrorLabel) &&
        ValidationUtil.isValidName(name, NameErrorLabel) &&
        ValidationUtil.isValidReligion(religion, ReligionErrorLabel) &&
        ValidationUtil.isValidAge(age, AgeErrorLabel)&&
        ValidationUtil.isValidHeight(height, HeightErrorLabel) &&
        ValidationUtil.isValidJob(job, JobErrorLabel) &&
        ValidationUtil.isValidSalary(salary, SalaryErrorLabel) &&
        ValidationUtil.isValidGender(gender, GenderErrorLabel);
        boolean matchfound = false;
        if(isValid){
            PartnerModel partner = new PartnerModel(id, name, religion, Short.parseShort(age),height, job, Integer.valueOf(salary), gender);
            for(PartnerModel part : availablePartners){
                if(part.getId().equals(partner.getId())){
                    availablePartners.remove(part);
                    registertoAvailableTable();
                    matchfound = true;
                }
            }
            if (!matchfound){
                IdErrorLabel.setText("Id doesnt exist");
            }

        }
    }//GEN-LAST:event_DeleteButtonAdminActionPerformed

    private void MarriedButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarriedButtonAdminActionPerformed
        String id = TfPartnerId.getText();
        String name = TfPartnerName.getText();
        String religion = (String)TfPartnerReligion.getSelectedItem();
        String height = (String)TfPartnerHeight.getSelectedItem();
        String age = TfPartnerAge.getText();
        String job = TfPartnerJob.getText();
        String salary = TfPartnerSalary.getText();
        String gender = (String)TfPartnerGender.getSelectedItem();
        boolean isValid = ValidationUtil.isValidId(id, IdErrorLabel) &&
        ValidationUtil.isValidName(name, NameErrorLabel) &&
        ValidationUtil.isValidReligion(religion, ReligionErrorLabel) &&
        ValidationUtil.isValidAge(age, AgeErrorLabel)&&
        ValidationUtil.isValidHeight(height, HeightErrorLabel) &&
        ValidationUtil.isValidJob(job, JobErrorLabel) &&
        ValidationUtil.isValidSalary(salary, SalaryErrorLabel) &&
        ValidationUtil.isValidGender(gender, GenderErrorLabel);
        boolean matchfound = false;
        if(isValid){
            PartnerModel partner = new PartnerModel(id, name, religion, Short.parseShort(age),height, job, Integer.valueOf(salary), gender);
            for(PartnerModel part : availablePartners){
                if(part.getId().equals(partner.getId())){
                    availablePartners.remove(part);
                    marriedPartners.add(part);
                    registertoAvailableTable();
                    matchfound = true;
                }
            }
            if (!matchfound){
                IdErrorLabel.setText("Id doesnt exist");
            }

        }
    }//GEN-LAST:event_MarriedButtonAdminActionPerformed

    private void AboutusButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutusButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutusButtonHomeActionPerformed

    private void DatabaseButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseButtonHomeActionPerformed
        loadScreen("DatabaseScreen");
    }//GEN-LAST:event_DatabaseButtonHomeActionPerformed

    private void AdminButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonHomeActionPerformed
        loadScreen("AdminScreen");
    }//GEN-LAST:event_AdminButtonHomeActionPerformed

    private void HomeButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonHomeActionPerformed
        loadScreen("HomeScreen");
    }//GEN-LAST:event_HomeButtonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutusButtonAdmin;
    private javax.swing.JButton AboutusButtonDatabase;
    private javax.swing.JButton AboutusButtonHome;
    private javax.swing.JButton AboutusButtonHome2;
    private javax.swing.JPanel AboutusPanel;
    private javax.swing.JButton AddButtonAdmin;
    private javax.swing.JButton AdminButtonAdmin;
    private javax.swing.JButton AdminButtonAdmin2;
    private javax.swing.JButton AdminButtonDatabase;
    private javax.swing.JButton AdminButtonHome;
    private javax.swing.JLabel AdminImage;
    private javax.swing.JLabel AdminImage2;
    private javax.swing.JLabel AdminMessageLabel;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JLabel AgeErrorLabel;
    private javax.swing.JTable AvailableTable;
    private javax.swing.JScrollPane AvailableTablePanel;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JButton DatabaseButtonAdmin;
    private javax.swing.JButton DatabaseButtonDatabase;
    private javax.swing.JButton DatabaseButtonHome;
    private javax.swing.JButton DatabaseButtonHome2;
    private javax.swing.JLabel DatabaseImage;
    private javax.swing.JPanel DatabasePanel;
    private javax.swing.JButton DeleteButtonAdmin;
    private javax.swing.JLabel GenderErrorLabel;
    private javax.swing.JLabel HeightErrorLabel;
    private javax.swing.JButton HomeButtonAdmin;
    private javax.swing.JButton HomeButtonDatabase;
    private javax.swing.JButton HomeButtonHome;
    private javax.swing.JButton HomeButtonHome2;
    private javax.swing.JLabel HomePageImage;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel IdErrorLabel;
    private javax.swing.JLabel IncorrectLabelLogin;
    private javax.swing.JLabel JobErrorLabel;
    private javax.swing.JPanel LoadingPanel;
    private javax.swing.JLabel LoadingScreenImage;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LogoMessageLabel;
    private javax.swing.JLabel LogoMessageLabel1;
    private javax.swing.JLabel LogoMessageLabel2;
    private javax.swing.JLabel LogoMessageLabel3;
    private javax.swing.JButton MarriedButtonAdmin;
    private javax.swing.JLabel NameErrorLabel;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel ReligionErrorLabel;
    private javax.swing.JLabel SalaryErrorLabel;
    private javax.swing.JPasswordField TfLoginPassword;
    private javax.swing.JTextField TfLoginUsername;
    private javax.swing.JTextField TfPartnerAge;
    private javax.swing.JComboBox<String> TfPartnerGender;
    private javax.swing.JComboBox<String> TfPartnerHeight;
    private javax.swing.JTextField TfPartnerId;
    private javax.swing.JTextField TfPartnerJob;
    private javax.swing.JTextField TfPartnerName;
    private javax.swing.JComboBox<String> TfPartnerReligion;
    private javax.swing.JTextField TfPartnerSalary;
    private javax.swing.JButton UpdateButtonAdmin;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel WelcomeMessagelabel;
    private javax.swing.JLabel WelcomeMessagelabel1;
    private javax.swing.JLabel WelcomeMessagelabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
}
