/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.garbhawati.view;

import com.garbhawati.controller.ValidationUtil;
import com.garbhawati.model.PartnerModel;
import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itiss
 */
public class Garbhawati extends javax.swing.JFrame {
    private List<PartnerModel> availablePartners;
    private List<PartnerModel> marriedPartners;
    private java.awt.CardLayout cardLayout;

    /**
     * Creates new form NewJFrame
     */
    public Garbhawati() {
        initComponents();
        initializeLayout();
        availablePartners = new LinkedList();
        marriedPartners = new LinkedList();
    }
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(LoginPanel, "LoginScreen");
        getContentPane().add(MainPanel, "MainScreen");
        getContentPane().add(AdminPanel, "AdminScreen");

        // Start with the loading screen
        cardLayout.show(getContentPane(), "LoadingScreen");
    }
    
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    private void registertoAvailableTable(){
        DefaultTableModel model = (DefaultTableModel) AvailableTable.getModel();
        model.setRowCount(0);
        for(PartnerModel partner : availablePartners){
            model.addRow(new Object[]{partner.getId(), partner.getName(), partner.getReligion(), partner.getHeight(), partner.getAge(), partner.getJob(), partner.getSalary(), partner.getGender()});
        }
    }
    private void registertoMarriedTable(){
        DefaultTableModel model = (DefaultTableModel) MarriedTable.getModel();
        model.setRowCount(0);
        for(PartnerModel partner : marriedPartners){
            model.addRow(new Object[]{partner.getId(), partner.getName(),partner.getHeight(), partner.getAge(), partner.getReligion(), partner.getJob(), partner.getSalary(), partner.getGender()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminFrame = new javax.swing.JFrame();
        AdminPanel = new javax.swing.JPanel();
        NavBarAdminPanel = new javax.swing.JPanel();
        AdminLogoLabel = new javax.swing.JLabel();
        HomeButtonAdmin = new javax.swing.JButton();
        AdminButtonAdmin = new javax.swing.JButton();
        AboutusButtonAdmin = new javax.swing.JButton();
        CompanyNameLabelAdmin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AvailableTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        TfPartnerId = new javax.swing.JTextField();
        TfPartnerName = new javax.swing.JTextField();
        TfPartnerAge = new javax.swing.JTextField();
        TfPartnerJob = new javax.swing.JTextField();
        TfPartnerSalary = new javax.swing.JTextField();
        TfPartnerReligion = new javax.swing.JComboBox<>();
        TfPartnerGender = new javax.swing.JComboBox<>();
        TfPartnerHeight = new javax.swing.JComboBox<>();
        AddButtonAdmin = new javax.swing.JButton();
        UpdateButtonAdmin = new javax.swing.JButton();
        DeleteButtonAdmin = new javax.swing.JButton();
        MarriedButtonAdmin = new javax.swing.JButton();
        IdErrorLabel = new javax.swing.JLabel();
        NameErrorLabel = new javax.swing.JLabel();
        AgeErrorLabel = new javax.swing.JLabel();
        ReligionErrorLabel = new javax.swing.JLabel();
        HeightErrorLabel = new javax.swing.JLabel();
        JobErrorLabel = new javax.swing.JLabel();
        SalaryErrorLabel = new javax.swing.JLabel();
        GenderErrorLabel = new javax.swing.JLabel();
        MainFrame = new javax.swing.JFrame();
        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HomeButtonMain = new javax.swing.JButton();
        HomeButtonMain1 = new javax.swing.JButton();
        HomeButtonMain2 = new javax.swing.JButton();
        HomeButtonMain3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MarriedTable = new javax.swing.JTable();
        AboutusFrame = new javax.swing.JFrame();
        MainPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        HomeButtonMain12 = new javax.swing.JButton();
        HomeButtonMain13 = new javax.swing.JButton();
        HomeButtonMain14 = new javax.swing.JButton();
        HomeButtonMain15 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        LoginImageLabel = new javax.swing.JLabel();
        WelcomeLoginLabel = new javax.swing.JLabel();
        TfLoginUsername = new javax.swing.JTextField();
        TfLoginPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        IncorrectLableLogin = new javax.swing.JLabel();

        AdminFrame.setMaximumSize(new java.awt.Dimension(1280, 720));
        AdminFrame.setMinimumSize(new java.awt.Dimension(1280, 720));
        AdminFrame.setPreferredSize(new java.awt.Dimension(1280, 720));
        AdminFrame.setSize(new java.awt.Dimension(1280, 720));

        AdminPanel.setBackground(new java.awt.Color(248, 250, 252));
        AdminPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        AdminPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        AdminPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        NavBarAdminPanel.setBackground(new java.awt.Color(217, 234, 253));
        NavBarAdminPanel.setMaximumSize(new java.awt.Dimension(1920, 70));
        NavBarAdminPanel.setMinimumSize(new java.awt.Dimension(1920, 70));
        NavBarAdminPanel.setPreferredSize(new java.awt.Dimension(1920, 70));

        AdminLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/couple-with-lovely-wedding-flat-style-isolated-background_1375-17429-removebg-preview (3).png"))); // NOI18N

        HomeButtonAdmin.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonAdmin.setText("Home");
        HomeButtonAdmin.setBorder(null);
        HomeButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonAdminActionPerformed(evt);
            }
        });

        AdminButtonAdmin.setBackground(new java.awt.Color(217, 234, 253));
        AdminButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        AdminButtonAdmin.setText("Admin");
        AdminButtonAdmin.setBorder(null);
        AdminButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonAdminActionPerformed(evt);
            }
        });

        AboutusButtonAdmin.setBackground(new java.awt.Color(217, 234, 253));
        AboutusButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        AboutusButtonAdmin.setText("About us");
        AboutusButtonAdmin.setBorder(null);
        AboutusButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutusButtonAdminActionPerformed(evt);
            }
        });

        CompanyNameLabelAdmin.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 36)); // NOI18N
        CompanyNameLabelAdmin.setText("Patni.com");

        javax.swing.GroupLayout NavBarAdminPanelLayout = new javax.swing.GroupLayout(NavBarAdminPanel);
        NavBarAdminPanel.setLayout(NavBarAdminPanelLayout);
        NavBarAdminPanelLayout.setHorizontalGroup(
            NavBarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarAdminPanelLayout.createSequentialGroup()
                .addComponent(AdminLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CompanyNameLabelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492)
                .addComponent(HomeButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(AdminButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(AboutusButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(812, Short.MAX_VALUE))
        );
        NavBarAdminPanelLayout.setVerticalGroup(
            NavBarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarAdminPanelLayout.createSequentialGroup()
                .addGroup(NavBarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarAdminPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(NavBarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AboutusButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NavBarAdminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AdminLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavBarAdminPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CompanyNameLabelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(217, 234, 253));
        jPanel2.setMaximumSize(new java.awt.Dimension(1920, 1010));
        jPanel2.setMinimumSize(new java.awt.Dimension(1920, 1010));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1010));

        AvailableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Religion", "Height", "Age", "Job", "Salary", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(AvailableTable);
        if (AvailableTable.getColumnModel().getColumnCount() > 0) {
            AvailableTable.getColumnModel().getColumn(0).setResizable(false);
            AvailableTable.getColumnModel().getColumn(1).setResizable(false);
            AvailableTable.getColumnModel().getColumn(2).setResizable(false);
            AvailableTable.getColumnModel().getColumn(3).setResizable(false);
            AvailableTable.getColumnModel().getColumn(4).setResizable(false);
            AvailableTable.getColumnModel().getColumn(5).setResizable(false);
            AvailableTable.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        jLabel3.setText("Add a new Partner");

        TfPartnerId.setText("ID");
        TfPartnerId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerIdMouseClicked(evt);
            }
        });

        TfPartnerName.setText("Name");
        TfPartnerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerNameMouseClicked(evt);
            }
        });
        TfPartnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPartnerNameActionPerformed(evt);
            }
        });

        TfPartnerAge.setText("Age");
        TfPartnerAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerAgeMouseClicked(evt);
            }
        });

        TfPartnerJob.setText("Job");
        TfPartnerJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerJobMouseClicked(evt);
            }
        });

        TfPartnerSalary.setText("Salary");
        TfPartnerSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerSalaryMouseClicked(evt);
            }
        });
        TfPartnerSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPartnerSalaryActionPerformed(evt);
            }
        });

        TfPartnerReligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Religion", "Hinduism", "Buddhism", "Islam", "Kirant", "Christianity", "Bon", "Others" }));
        TfPartnerReligion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerReligionMouseClicked(evt);
            }
        });

        TfPartnerGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Others" }));
        TfPartnerGender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerGenderMouseClicked(evt);
            }
        });
        TfPartnerGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPartnerGenderActionPerformed(evt);
            }
        });

        TfPartnerHeight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Height", "5'0", "5'1", "5'2", "5'3", "5'4", "5'5", "5'6", "5'7", "5'8", "5'9", "5'10", "5'11", "6'0", "6'1", "6'2", "6'3", "6'4", "6'5" }));
        TfPartnerHeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfPartnerHeightMouseClicked(evt);
            }
        });

        AddButtonAdmin.setBackground(new java.awt.Color(0, 0, 0));
        AddButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        AddButtonAdmin.setForeground(new java.awt.Color(248, 250, 252));
        AddButtonAdmin.setText("Add");
        AddButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonAdminActionPerformed(evt);
            }
        });

        UpdateButtonAdmin.setBackground(new java.awt.Color(0, 0, 0));
        UpdateButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        UpdateButtonAdmin.setForeground(new java.awt.Color(248, 250, 252));
        UpdateButtonAdmin.setText("Update");
        UpdateButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonAdminActionPerformed(evt);
            }
        });

        DeleteButtonAdmin.setBackground(new java.awt.Color(0, 0, 0));
        DeleteButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        DeleteButtonAdmin.setForeground(new java.awt.Color(248, 250, 252));
        DeleteButtonAdmin.setText("Delete");
        DeleteButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonAdminActionPerformed(evt);
            }
        });

        MarriedButtonAdmin.setBackground(new java.awt.Color(0, 0, 0));
        MarriedButtonAdmin.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        MarriedButtonAdmin.setForeground(new java.awt.Color(248, 250, 252));
        MarriedButtonAdmin.setText("Married");
        MarriedButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarriedButtonAdminActionPerformed(evt);
            }
        });

        IdErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        NameErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        AgeErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

        ReligionErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        HeightErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

        JobErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

        SalaryErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

        GenderErrorLabel.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(567, 567, 567)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(IdErrorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TfPartnerId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfPartnerName, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(NameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfPartnerReligion, 0, 226, Short.MAX_VALUE)
                                    .addComponent(ReligionErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfPartnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfPartnerHeight, 0, 226, Short.MAX_VALUE)
                                    .addComponent(HeightErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(JobErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(30, 30, 30))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TfPartnerJob, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SalaryErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TfPartnerSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfPartnerGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GenderErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MarriedButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AddButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(UpdateButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(143, 143, 143)
                        .addComponent(DeleteButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(754, 754, 754))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IdErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReligionErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPartnerId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPartnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPartnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPartnerReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HeightErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JobErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(SalaryErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPartnerJob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPartnerSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPartnerGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPartnerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(MarriedButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addComponent(NavBarAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1926, Short.MAX_VALUE)))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavBarAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AdminFrameLayout = new javax.swing.GroupLayout(AdminFrame.getContentPane());
        AdminFrame.getContentPane().setLayout(AdminFrameLayout);
        AdminFrameLayout.setHorizontalGroup(
            AdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AdminFrameLayout.setVerticalGroup(
            AdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MainFrame.setMinimumSize(new java.awt.Dimension(1920, 1080));
        MainFrame.setSize(new java.awt.Dimension(1920, 1080));

        MainPanel.setBackground(new java.awt.Color(248, 250, 252));
        MainPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(217, 234, 253));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/couple-with-lovely-wedding-flat-style-isolated-background_1375-17429-removebg-preview (3).png"))); // NOI18N

        HomeButtonMain.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonMain.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonMain.setText("Home");
        HomeButtonMain.setBorder(null);
        HomeButtonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonMainActionPerformed(evt);
            }
        });

        HomeButtonMain1.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonMain1.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonMain1.setText("Admin");
        HomeButtonMain1.setBorder(null);
        HomeButtonMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonMain1ActionPerformed(evt);
            }
        });

        HomeButtonMain2.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonMain2.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonMain2.setText("Database");
        HomeButtonMain2.setBorder(null);
        HomeButtonMain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonMain2ActionPerformed(evt);
            }
        });

        HomeButtonMain3.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonMain3.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonMain3.setText("About us");
        HomeButtonMain3.setBorder(null);
        HomeButtonMain3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonMain3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 36)); // NOI18N
        jLabel2.setText("Patni.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1117, Short.MAX_VALUE)
                .addComponent(HomeButtonMain, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(HomeButtonMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(HomeButtonMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(HomeButtonMain3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HomeButtonMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HomeButtonMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HomeButtonMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HomeButtonMain3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(217, 234, 253));

        jLabel4.setFont(new java.awt.Font("Brush Script MT", 0, 100)); // NOI18N
        jLabel4.setText("Congratulations");

        MarriedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Religion", "Age", "Height", "Job", "Salary", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MarriedTable);
        if (MarriedTable.getColumnModel().getColumnCount() > 0) {
            MarriedTable.getColumnModel().getColumn(0).setResizable(false);
            MarriedTable.getColumnModel().getColumn(1).setResizable(false);
            MarriedTable.getColumnModel().getColumn(2).setResizable(false);
            MarriedTable.getColumnModel().getColumn(3).setResizable(false);
            MarriedTable.getColumnModel().getColumn(4).setResizable(false);
            MarriedTable.getColumnModel().getColumn(5).setResizable(false);
            MarriedTable.getColumnModel().getColumn(6).setResizable(false);
            MarriedTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainFrameLayout = new javax.swing.GroupLayout(MainFrame.getContentPane());
        MainFrame.getContentPane().setLayout(MainFrameLayout);
        MainFrameLayout.setHorizontalGroup(
            MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainFrameLayout.setVerticalGroup(
            MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AboutusFrame.setMinimumSize(new java.awt.Dimension(1920, 1080));
        AboutusFrame.setSize(new java.awt.Dimension(1920, 1080));

        MainPanel3.setBackground(new java.awt.Color(248, 250, 252));
        MainPanel3.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel4.setBackground(new java.awt.Color(217, 234, 253));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/couple-with-lovely-wedding-flat-style-isolated-background_1375-17429-removebg-preview (3).png"))); // NOI18N

        HomeButtonMain12.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonMain12.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonMain12.setText("Home");
        HomeButtonMain12.setBorder(null);
        HomeButtonMain12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonMain12ActionPerformed(evt);
            }
        });

        HomeButtonMain13.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonMain13.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonMain13.setText("Admin");
        HomeButtonMain13.setBorder(null);
        HomeButtonMain13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonMain13ActionPerformed(evt);
            }
        });

        HomeButtonMain14.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonMain14.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonMain14.setText("Database");
        HomeButtonMain14.setBorder(null);
        HomeButtonMain14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonMain14ActionPerformed(evt);
            }
        });

        HomeButtonMain15.setBackground(new java.awt.Color(217, 234, 253));
        HomeButtonMain15.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        HomeButtonMain15.setText("About us");
        HomeButtonMain15.setBorder(null);
        HomeButtonMain15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonMain15ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 36)); // NOI18N
        jLabel8.setText("Patni.com");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1117, Short.MAX_VALUE)
                .addComponent(HomeButtonMain12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(HomeButtonMain13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(HomeButtonMain14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(HomeButtonMain15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeButtonMain12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeButtonMain13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeButtonMain14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeButtonMain15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanel3Layout = new javax.swing.GroupLayout(MainPanel3);
        MainPanel3.setLayout(MainPanel3Layout);
        MainPanel3Layout.setHorizontalGroup(
            MainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MainPanel3Layout.setVerticalGroup(
            MainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(993, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AboutusFrameLayout = new javax.swing.GroupLayout(AboutusFrame.getContentPane());
        AboutusFrame.getContentPane().setLayout(AboutusFrameLayout);
        AboutusFrameLayout.setHorizontalGroup(
            AboutusFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AboutusFrameLayout.setVerticalGroup(
            AboutusFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        LoginPanel.setBackground(new java.awt.Color(248, 250, 252));
        LoginPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        LoginPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        LoginPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        LoginImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/—Pngtree—indian wedding mehendi couple for_8874101 (1).png"))); // NOI18N

        WelcomeLoginLabel.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 48)); // NOI18N
        WelcomeLoginLabel.setText("Welcome");

        TfLoginUsername.setBackground(new java.awt.Color(248, 250, 252));
        TfLoginUsername.setText("Username");
        TfLoginUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TfLoginUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfLoginUsernameMouseClicked(evt);
            }
        });

        TfLoginPassword.setBackground(new java.awt.Color(248, 250, 252));
        TfLoginPassword.setText("Password");
        TfLoginPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TfLoginPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfLoginPasswordMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Baloo 2", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(248, 250, 252));
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IncorrectLableLogin.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LoginImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(WelcomeLoginLabel))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(IncorrectLableLogin)))
                .addContainerGap(843, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(WelcomeLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IncorrectLableLogin)
                        .addGap(41, 41, 41)
                        .addComponent(TfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TfLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(LoginImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfLoginUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfLoginUsernameMouseClicked
        TfLoginUsername.setText("");
        IncorrectLableLogin.setText("");
        
    }//GEN-LAST:event_TfLoginUsernameMouseClicked

    private void TfLoginPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfLoginPasswordMouseClicked
        TfLoginPassword.setText("");
        IncorrectLableLogin.setText("");
    }//GEN-LAST:event_TfLoginPasswordMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Username = TfLoginUsername.getText();
        String Password = new String(TfLoginPassword.getPassword());
        
        if ("Username".equals(Username) && "Password".equals(Password)){
            loadScreen("MainScreen");
        }
        else{
            IncorrectLableLogin.setText("Incorrect Username or Password");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HomeButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMainActionPerformed

    private void HomeButtonMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonMain1ActionPerformed
        loadScreen("AdminScreen");
    }//GEN-LAST:event_HomeButtonMain1ActionPerformed

    private void HomeButtonMain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonMain2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMain2ActionPerformed

    private void HomeButtonMain3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonMain3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMain3ActionPerformed

    private void HomeButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonAdminActionPerformed
        loadScreen("MainScreen");
    }//GEN-LAST:event_HomeButtonAdminActionPerformed

    private void AdminButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonAdminActionPerformed
        loadScreen("AdminScreen");
    }//GEN-LAST:event_AdminButtonAdminActionPerformed

    private void AboutusButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutusButtonAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutusButtonAdminActionPerformed

    private void HomeButtonMain12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonMain12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMain12ActionPerformed

    private void HomeButtonMain13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonMain13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMain13ActionPerformed

    private void HomeButtonMain14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonMain14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMain14ActionPerformed

    private void HomeButtonMain15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonMain15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMain15ActionPerformed

    private void TfPartnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPartnerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPartnerNameActionPerformed

    private void TfPartnerSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPartnerSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPartnerSalaryActionPerformed

    private void DeleteButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonAdminActionPerformed
        String id = TfPartnerId.getText();
        String name = TfPartnerName.getText();
        String religion = (String)TfPartnerReligion.getSelectedItem();
        String height = (String)TfPartnerHeight.getSelectedItem();
        String age = TfPartnerAge.getText();
        String job = TfPartnerJob.getText();
        String salary = TfPartnerSalary.getText();
        String gender = (String)TfPartnerGender.getSelectedItem();
        boolean isValid = ValidationUtil.isValidId(id, IdErrorLabel) &&
                          ValidationUtil.isValidName(name, NameErrorLabel) &&
                          ValidationUtil.isValidReligion(religion, ReligionErrorLabel) &&
                          ValidationUtil.isValidAge(age, AgeErrorLabel)&&
                          ValidationUtil.isValidHeight(height, HeightErrorLabel) &&
                          ValidationUtil.isValidJob(job, JobErrorLabel) &&
                          ValidationUtil.isValidSalary(salary, SalaryErrorLabel) &&
                          ValidationUtil.isValidGender(gender, GenderErrorLabel);  
        boolean matchfound = false;
        if(isValid){
            PartnerModel partner = new PartnerModel(id, name, religion, Short.parseShort(age),height, job, Integer.valueOf(salary), gender);
            for(PartnerModel part : availablePartners){
                if(part.getId().equals(partner.getId())){
                    availablePartners.remove(part);
                    registertoAvailableTable();
                    matchfound = true;
                }
            }
            if (!matchfound){
                IdErrorLabel.setText("Id doesnt exist");
            }
                
        }
    }//GEN-LAST:event_DeleteButtonAdminActionPerformed

    private void AddButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonAdminActionPerformed
        String id = TfPartnerId.getText();
        String name = TfPartnerName.getText();
        String religion = (String)TfPartnerReligion.getSelectedItem();
        String height = (String)TfPartnerHeight.getSelectedItem();
        String age = TfPartnerAge.getText();
        String job = TfPartnerJob.getText();
        String salary = TfPartnerSalary.getText();
        String gender = (String)TfPartnerGender.getSelectedItem();
        boolean isValid = ValidationUtil.isValidId(id, IdErrorLabel) &&
                          ValidationUtil.isValidName(name, NameErrorLabel) &&
                          ValidationUtil.isValidReligion(religion, ReligionErrorLabel) &&
                          ValidationUtil.isValidAge(age, AgeErrorLabel)&&
                          ValidationUtil.isValidHeight(height, HeightErrorLabel) &&
                          ValidationUtil.isValidJob(job, JobErrorLabel) &&
                          ValidationUtil.isValidSalary(salary, SalaryErrorLabel) &&
                          ValidationUtil.isValidGender(gender, GenderErrorLabel);
        boolean matchfound = false;
        if (isValid){
            PartnerModel partner = new PartnerModel(id, name, religion, Short.parseShort(age),height, job, Integer.valueOf(salary), gender);
            for (PartnerModel part : availablePartners){
                if (part.getId().equals(partner.getId())){
                    matchfound = true;
                }
            }
            if (matchfound){
                IdErrorLabel.setText("Id already Exists");
            }
            else{
                availablePartners.add(partner);
                registertoAvailableTable();
            }
        }       
    }//GEN-LAST:event_AddButtonAdminActionPerformed

    private void TfPartnerGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPartnerGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPartnerGenderActionPerformed

    private void TfPartnerIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerIdMouseClicked
        IdErrorLabel.setText("");
        TfPartnerId.setText("");
    }//GEN-LAST:event_TfPartnerIdMouseClicked

    private void TfPartnerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerNameMouseClicked
        NameErrorLabel.setText("");
        TfPartnerName.setText("");
    }//GEN-LAST:event_TfPartnerNameMouseClicked

    private void TfPartnerReligionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerReligionMouseClicked
        ReligionErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerReligionMouseClicked

    private void TfPartnerAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerAgeMouseClicked
        AgeErrorLabel.setText("");
        TfPartnerAge.setText("");
    }//GEN-LAST:event_TfPartnerAgeMouseClicked

    private void TfPartnerHeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerHeightMouseClicked
        HeightErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerHeightMouseClicked

    private void TfPartnerJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerJobMouseClicked
        TfPartnerJob.setText("");
        JobErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerJobMouseClicked

    private void TfPartnerSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerSalaryMouseClicked
       TfPartnerSalary.setText("");
       SalaryErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerSalaryMouseClicked

    private void TfPartnerGenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfPartnerGenderMouseClicked
        GenderErrorLabel.setText("");
    }//GEN-LAST:event_TfPartnerGenderMouseClicked

    private void UpdateButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonAdminActionPerformed
        String id = TfPartnerId.getText();
        String name = TfPartnerName.getText();
        String religion = (String)TfPartnerReligion.getSelectedItem();
        String height = (String)TfPartnerHeight.getSelectedItem();
        String age = TfPartnerAge.getText();
        String job = TfPartnerJob.getText();
        String salary = TfPartnerSalary.getText();
        String gender = (String)TfPartnerGender.getSelectedItem();
        boolean isValid = ValidationUtil.isValidId(id, IdErrorLabel) &&
                          ValidationUtil.isValidName(name, NameErrorLabel) &&
                          ValidationUtil.isValidReligion(religion, ReligionErrorLabel) &&
                          ValidationUtil.isValidAge(age, AgeErrorLabel)&&
                          ValidationUtil.isValidHeight(height, HeightErrorLabel) &&
                          ValidationUtil.isValidJob(job, JobErrorLabel) &&
                          ValidationUtil.isValidSalary(salary, SalaryErrorLabel) &&
                          ValidationUtil.isValidGender(gender, GenderErrorLabel);  
        boolean matchfound = false;
        if(isValid){
            PartnerModel partner = new PartnerModel(id, name, religion, Short.parseShort(age),height, job, Integer.valueOf(salary), gender);
            for(PartnerModel part : availablePartners){
                if(part.getId().equals(partner.getId())){
                    availablePartners.remove(part);
                    availablePartners.add(partner);
                    registertoAvailableTable();
                    matchfound = true;
                }
            }
            if (!matchfound){
                IdErrorLabel.setText("Id doesnt exist");
            }
                
        }
    }//GEN-LAST:event_UpdateButtonAdminActionPerformed

    private void MarriedButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarriedButtonAdminActionPerformed
        String id = TfPartnerId.getText();
        String name = TfPartnerName.getText();
        String religion = (String)TfPartnerReligion.getSelectedItem();
        String height = (String)TfPartnerHeight.getSelectedItem();
        String age = TfPartnerAge.getText();
        String job = TfPartnerJob.getText();
        String salary = TfPartnerSalary.getText();
        String gender = (String)TfPartnerGender.getSelectedItem();
        boolean isValid = ValidationUtil.isValidId(id, IdErrorLabel) &&
                          ValidationUtil.isValidName(name, NameErrorLabel) &&
                          ValidationUtil.isValidReligion(religion, ReligionErrorLabel) &&
                          ValidationUtil.isValidAge(age, AgeErrorLabel)&&
                          ValidationUtil.isValidHeight(height, HeightErrorLabel) &&
                          ValidationUtil.isValidJob(job, JobErrorLabel) &&
                          ValidationUtil.isValidSalary(salary, SalaryErrorLabel) &&
                          ValidationUtil.isValidGender(gender, GenderErrorLabel);  
        boolean matchfound = false;
        if(isValid){
            PartnerModel partner = new PartnerModel(id, name, religion, Short.parseShort(age),height, job, Integer.valueOf(salary), gender);
            for(PartnerModel part : availablePartners){
                if(part.getId().equals(partner.getId())){
                    availablePartners.remove(part);
                    marriedPartners.add(part);
                    registertoAvailableTable();
                    registertoMarriedTable();
                    matchfound = true;
                }
            }
            if (!matchfound){
                IdErrorLabel.setText("Id doesnt exist");
            }
                
        }
    }//GEN-LAST:event_MarriedButtonAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Garbhawati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Garbhawati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Garbhawati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Garbhawati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Garbhawati().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutusButtonAdmin;
    private javax.swing.JFrame AboutusFrame;
    private javax.swing.JButton AddButtonAdmin;
    private javax.swing.JButton AdminButtonAdmin;
    private javax.swing.JFrame AdminFrame;
    private javax.swing.JLabel AdminLogoLabel;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JLabel AgeErrorLabel;
    private javax.swing.JTable AvailableTable;
    private javax.swing.JLabel CompanyNameLabelAdmin;
    private javax.swing.JButton DeleteButtonAdmin;
    private javax.swing.JLabel GenderErrorLabel;
    private javax.swing.JLabel HeightErrorLabel;
    private javax.swing.JButton HomeButtonAdmin;
    private javax.swing.JButton HomeButtonMain;
    private javax.swing.JButton HomeButtonMain1;
    private javax.swing.JButton HomeButtonMain12;
    private javax.swing.JButton HomeButtonMain13;
    private javax.swing.JButton HomeButtonMain14;
    private javax.swing.JButton HomeButtonMain15;
    private javax.swing.JButton HomeButtonMain2;
    private javax.swing.JButton HomeButtonMain3;
    private javax.swing.JLabel IdErrorLabel;
    private javax.swing.JLabel IncorrectLableLogin;
    private javax.swing.JLabel JobErrorLabel;
    private javax.swing.JLabel LoginImageLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JFrame MainFrame;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MainPanel3;
    private javax.swing.JButton MarriedButtonAdmin;
    private javax.swing.JTable MarriedTable;
    private javax.swing.JLabel NameErrorLabel;
    private javax.swing.JPanel NavBarAdminPanel;
    private javax.swing.JLabel ReligionErrorLabel;
    private javax.swing.JLabel SalaryErrorLabel;
    private javax.swing.JPasswordField TfLoginPassword;
    private javax.swing.JTextField TfLoginUsername;
    private javax.swing.JTextField TfPartnerAge;
    private javax.swing.JComboBox<String> TfPartnerGender;
    private javax.swing.JComboBox<String> TfPartnerHeight;
    private javax.swing.JTextField TfPartnerId;
    private javax.swing.JTextField TfPartnerJob;
    private javax.swing.JTextField TfPartnerName;
    private javax.swing.JComboBox<String> TfPartnerReligion;
    private javax.swing.JTextField TfPartnerSalary;
    private javax.swing.JButton UpdateButtonAdmin;
    private javax.swing.JLabel WelcomeLoginLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
